import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

function Home(){
  return (
    <div className={styles.container}>
      <Head>
        <title>Web Chat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles['message-list']}>

      </div>
    </div>

      
  )
}

export default Home
